import { Images } from "lucide-react"

// ─────────────────────────────────────────────────────────────────────────────
// Tour: Crear una galería
//
// REGLA DE SELECTORES (para que el spotlight funcione):
//  - selectorText  → busca en button/a/[role=button] por textContent exacto
//                    Úsarlo para BOTONES que el usuario debe hacer clic
//  - selector CSS  → para inputs, selects, labels o contenedores que no son botones
//  - null en ambos → paso informativo sin spotlight (card flota sin blur de fondo)
//
// Árbol de ramas:
//   steps → pregunta "¿Qué tipo?" → branchYes (Evento) | branchNo (Estándar)
//   branchNo → pregunta "¿Cobrar?" → branchYes (Estándar paga) | branchNo (Gratuita)
// ─────────────────────────────────────────────────────────────────────────────

const galeriesTour = {
    id: "create-gallery",
    icon: Images,
    iconBg: "linear-gradient(135deg,#eff6ff,#dbeafe)",
    iconColor: "#3b82f6",
    title: "Crear una galería",
    description: "Te guío paso a paso para crear y configurar tu primera galería fotográfica.",
    estimatedTime: "5 min",
    steps: [
        {
            id: "intro",
            title: "Vamos a crear tu galería 📸",
            body: "Una galería es el espacio donde entregás las fotos de un trabajo a tus clientes. Puede ser pública o privada, gratuita o paga, estándar o de evento. Este tour cubre todo.",
            route: "/dashboard/galleries",
            selector: null,
            selectorText: null,
        },
        {
            id: "go-galleries",
            title: "Ir a Galerías",
            body: "En el menú lateral (o en el ☰ en celular), hacé clic en «Galerías» para ver tus álbumes.",
            route: "/dashboard/galleries",
            selector: "a[href='/dashboard/galleries']",
            selectorText: null,
            tip: "Desde ahí también podés ver y gestionar las galerías que ya tenés.",
        },
        {
            id: "new-gallery-btn",
            title: "Crear nueva galería",
            body: "Hacé clic en el botón «Nueva» para abrir el formulario de creación.",
            route: "/dashboard/galleries",
            selectorText: "Nueva",
            selectorFallbackText: "Crear primera galería",
            tip: "Si el botón está deshabilitado, revisá que tu plan no haya llegado al límite de galerías.",
        },
        {
            id: "gallery-title",
            title: "Dale un título claro",
            body: "Escribí un nombre descriptivo. Un buen título ayuda a tus clientes a identificar su trabajo al instante. Por ejemplo: «Casamiento García – Nov 2024».",
            route: "/dashboard/galleries/new",
            selector: "#title",
            selectorText: null,
            tip: "Incluí el nombre del cliente y la fecha: es lo más fácil para buscarlo después.",
        },
        {
            id: "gallery-description",
            title: "Descripción (opcional)",
            body: "Podés agregar una descripción breve. Aparece en la galería pública y le da más contexto al cliente.",
            route: "/dashboard/galleries/new",
            selector: "#description",
            selectorText: null,
            tip: "Algo simple como «Sesión de boda en Mendoza, 15 de noviembre» ya está perfecto.",
        },
        {
            id: "gallery-type-section",
            title: "Tipo de galería",
            body: "Esta sección define el comportamiento de la galería. «Estándar» es para entregas donde solo vos subís fotos. «Evento» permite que los invitados también suban las suyas, con QR y búsqueda facial.",
            route: "/dashboard/galleries/new",
            selector: null,
            selectorText: "Estándar",
            tip: "Si no ves el botón «Evento» activo, tu plan actual no lo incluye.",
        },
        {
            id: "gallery-type-question",
            title: "¿Qué tipo de galería necesitás?",
            body: "Elegí según el trabajo:\n\n• Estándar: retratos, familia, productos, arquitectura — solo vos subís fotos.\n\n• Evento: bodas, cumpleaños, fiestas — los invitados también pueden subir fotos y buscar las suyas con reconocimiento facial.",
            question: true,
            questionYes: "🎉 Evento (QR + invitados)",
            questionNo: "🖼️ Estándar",
        },
    ],

    // ── Rama: Galería de Evento ───────────────────────────────────────────────
    branchYes: [
        {
            id: "type-event-btn",
            title: "Seleccioná «Evento»",
            body: "Hacé clic en el botón «Evento» dentro de la sección Tipo de galería.",
            route: "/dashboard/galleries/new",
            selectorText: "Evento",
            tip: "Al seleccionarlo aparecen las opciones específicas del evento más abajo.",
        },
        {
            id: "event-pro-photos-label",
            title: "Fotos del fotógrafo: ¿con costo o gratis?",
            body: "En la opción «Fotos del fotógrafo» elegís si tus fotos profesionales tienen precio o son de descarga libre para todos los invitados.",
            route: "/dashboard/galleries/new",
            selectorText: "Con costo",
            tip: "«Con costo» es lo más común: los invitados pagan para descargar tus fotos. «Gratis» es ideal si el contratante ya pagó por todas.",
        },
        {
            id: "event-countdown",
            title: "Cuenta regresiva (opcional)",
            body: "Podés activar «Con cuenta regresiva» para que la galería muestre un contador hasta el inicio del evento. Muy útil para compartir el QR antes de que arranque.",
            route: "/dashboard/galleries/new",
            selectorText: "Con cuenta regresiva",
            tip: "Si activás esta opción, aparece un campo para ingresar la fecha y hora exacta del evento.",
        },
        {
            id: "event-start-input",
            title: "Fecha y hora del evento",
            body: "Si activaste la cuenta regresiva, completá acá la fecha y hora en que comienza el evento. Hasta ese momento los invitados verán el contador.",
            route: "/dashboard/galleries/new",
            selector: "#eventStartsAt",
            selectorText: null,
            tip: "Usá la hora real de inicio del evento, no la de llegada de los invitados.",
        },
        {
            id: "event-visibility-public",
            title: "Visibilidad: te recomendamos Pública",
            body: "En la sección «Visibilidad» elegís cómo acceden los invitados. Para eventos grandes, «Pública» es mejor — evitás la fricción de tener que repartir una contraseña en el momento.",
            route: "/dashboard/galleries/new",
            selectorText: "Pública",
            tip: "Si igual querés protegerla, usá «Privada» y preparate para compartir la contraseña junto al QR.",
        },
        {
            id: "event-password-input",
            title: "Contraseña (si elegiste Privada)",
            body: "Si la galería es privada, completá acá la contraseña. Debe tener al menos 4 caracteres. Elegí algo corto y fácil de tipear en celular.",
            route: "/dashboard/galleries/new",
            selector: "#password",
            selectorText: null,
            tip: "Evitá caracteres especiales como @, #, ! — en celular son difíciles de escribir rápido bajo presión.",
        },
        {
            id: "event-expiry-toggle",
            title: "Vencimiento de la galería",
            body: "En «Vencimiento y descargas» podés definir hasta cuándo estará disponible la galería. Para eventos, activar «Con vencimiento» una o dos semanas después es una buena práctica.",
            route: "/dashboard/galleries/new",
            selectorText: "Con vencimiento",
            tip: "Avisales a los invitados antes de que venza para que no se queden sin sus fotos.",
        },
        {
            id: "event-expiry-input",
            title: "Fecha de cierre",
            body: "Si activaste el vencimiento, elegí acá la fecha y hora en que la galería dejará de estar accesible.",
            route: "/dashboard/galleries/new",
            selector: "#expiresAt",
            selectorText: null,
            tip: "Después de esa fecha los invitados ya no podrán ver ni comprar fotos.",
        },
        {
            id: "event-download-duration",
            title: "Duración de links de descarga",
            body: "Definí por cuánto tiempo son válidos los links que reciben los invitados al descargar o comprar. Para eventos recomendamos 48 o 72 horas.",
            route: "/dashboard/galleries/new",
            selector: "#downloadLinkDuration",
            selectorText: null,
            tip: "Si alguien pierde el link, podés regenerarlo desde el panel de Órdenes.",
        },
        {
            id: "event-submit",
            title: "¡Todo listo! Creá la galería 🎊",
            body: "Revisá que todo esté bien y hacé clic en «Crear galería». Una vez creada vas a poder subir tus fotos y obtener el QR para compartir con los invitados.\n\n⚠️ Si ya usaste todas tus galerías de evento incluidas en el plan, aparecerá una opción de pago antes de crear.",
            route: "/dashboard/galleries/new",
            selector: "button[type='submit']",
            selectorText: "Crear galería",
            selectorFallbackText: "Pagar y crear galería",
            tip: "El QR lo encontrás dentro de la galería creada. Podés imprimirlo o enviarlo por WhatsApp.",
            final: true,
        },
    ],

    // ── Rama: Galería Estándar ────────────────────────────────────────────────
    branchNo: [
        {
            id: "type-standard-btn",
            title: "Seleccioná «Estándar»",
            body: "Hacé clic en el botón «Estándar» dentro de la sección Tipo de galería. Es la opción predeterminada.",
            route: "/dashboard/galleries/new",
            selectorText: "Estándar",
            tip: "En la galería estándar solo el fotógrafo puede subir contenido — ideal para entregas profesionales.",
        },
        {
            id: "standard-visibility-choice",
            title: "¿Pública o con contraseña?",
            body: "En «Visibilidad» elegís cómo acceden tus clientes. «Pública» significa que cualquiera con el link puede entrar. «Privada» requiere que el cliente ingrese una contraseña además del link.",
            route: "/dashboard/galleries/new",
            selectorText: "Privada",
            tip: "Para entregas a clientes particulares, la galería privada es la opción más profesional y segura.",
        },
        {
            id: "standard-password-input",
            title: "Configurá la contraseña",
            body: "Si elegiste galería privada, escribí acá la contraseña. Debe tener al menos 4 caracteres. Es lo que le vas a compartir al cliente junto con el link.",
            route: "/dashboard/galleries/new",
            selector: "#password",
            selectorText: null,
            tip: "Podés usar el apellido del cliente o algo fácil de recordar. Ej: garcia2024",
        },
        {
            id: "standard-paid-question",
            title: "¿Querés cobrar por las fotos?",
            body: "La galería puede ser gratuita — el cliente descarga sin pagar — o paga, donde cada foto o paquete tiene un precio. ¿Vas a vender las fotos?\n\nSi vas a cobrar, después de crear la galería configurás los precios desde la sección «Precios» dentro de la galería.",
            question: true,
            questionYes: "💰 Sí, quiero cobrar",
            questionNo: "🎁 No, entrega gratuita",
            branchYes: [
                {
                    id: "paid-pricing-info",
                    title: "Cómo configurar los precios 💰",
                    body: "Hay dos modalidades de precio:\n\n• «Por foto»: precio fijo por imagen — simple y directo.\n\n• «Por pack»: precio escalonado según cantidad comprada — a más fotos, más barato le sale cada una al cliente.\n\nEstas opciones las configurás desde la galería una vez creada, en la sección «Precios».",
                    route: "/dashboard/galleries/new",
                    selector: null,
                    selectorText: null,
                    tip: "El precio por pack incentiva al cliente a comprar más fotos: «5 por $5.000, 10 por $8.000, todas por $12.000».",
                },
                {
                    id: "paid-expiry-toggle",
                    title: "Vencimiento de la galería",
                    body: "En «Vencimiento y descargas» podés definir una fecha de cierre. Para galerías pagas, un límite de tiempo genera urgencia de compra.",
                    route: "/dashboard/galleries/new",
                    selectorText: "Con vencimiento",
                    tip: "Muchos fotógrafos usan 30 días: suficiente tiempo para decidir, pero con sensación de límite.",
                },
                {
                    id: "paid-expiry-input",
                    title: "Fecha de cierre",
                    body: "Si activaste el vencimiento, elegí acá la fecha y hora en que la galería dejará de estar accesible para compras.",
                    route: "/dashboard/galleries/new",
                    selector: "#expiresAt",
                    selectorText: null,
                    tip: "Después de esa fecha los clientes ya no podrán comprar ni descargar fotos.",
                },
                {
                    id: "paid-download-duration",
                    title: "Duración de links de descarga",
                    body: "Definí por cuánto tiempo son válidos los links que el cliente recibe después de pagar. 48 horas es el valor recomendado.",
                    route: "/dashboard/galleries/new",
                    selector: "#downloadLinkDuration",
                    selectorText: null,
                    tip: "Si el cliente no descarga a tiempo, podés regenerar el link desde el panel de Órdenes.",
                },
                {
                    id: "paid-printable",
                    title: "¿Vender versión impresa también?",
                    body: "Si tu plan lo incluye, en «Versión Imprimible» podés habilitar que el cliente elija entre digital, impresión física, o ambas. Los tamaños y precios de impresión se configuran dentro de la galería después de crearla.",
                    route: "/dashboard/galleries/new",
                    selectorText: "Digital + Impresión",
                    tip: "La venta de impresiones es un gran diferencial para bodas y retratos. Suma valor sin trabajo extra.",
                },
                {
                    id: "paid-submit",
                    title: "¡Listo para crear y cobrar! 🎉",
                    body: "Hacé clic en «Crear galería». Una vez creada, entrá a la galería y configurá los precios en la sección «Precios». Después subí las fotos y compartí el link.",
                    route: "/dashboard/galleries/new",
                    selector: "button[type='submit']",
                    selectorText: "Crear galería",
                    tip: "Recordá tener tu cuenta de Mercado Pago conectada en Configuración para poder recibir pagos.",
                    final: true,
                },
            ],
            branchNo: [
                {
                    id: "free-expiry-toggle",
                    title: "¿Querés que expire la galería?",
                    body: "En «Vencimiento y descargas» podés poner un cierre automático. Para entregas gratuitas es opcional, pero ayuda a mantener el orden si manejás muchos trabajos.",
                    route: "/dashboard/galleries/new",
                    selectorText: "Con vencimiento",
                    tip: "Muchos fotógrafos usan 90 días: tiempo más que suficiente para que el cliente descargue todo.",
                },
                {
                    id: "free-expiry-input",
                    title: "Fecha de cierre (si activaste vencimiento)",
                    body: "Si elegiste «Con vencimiento», configurá acá hasta cuándo estará disponible la galería.",
                    route: "/dashboard/galleries/new",
                    selector: "#expiresAt",
                    selectorText: null,
                    tip: "Después de esa fecha el cliente ya no podrá ver ni descargar las fotos.",
                },
                {
                    id: "free-download-duration",
                    title: "Duración de links de descarga",
                    body: "Cuando el cliente hace clic en «Descargar», recibe un link temporal. Acá definís por cuánto tiempo es válido ese link.",
                    route: "/dashboard/galleries/new",
                    selector: "#downloadLinkDuration",
                    selectorText: null,
                    tip: "Para entregas gratuitas podés elegir 7 días o más — así el cliente tiene tiempo de sobra.",
                },
                {
                    id: "free-submit",
                    title: "¡Galería gratuita lista! 🎉",
                    body: "Hacé clic en «Crear galería», subí las fotos y compartí el link con tu cliente. Pueden ver y descargar todo sin pagar.",
                    route: "/dashboard/galleries/new",
                    selector: "button[type='submit']",
                    selectorText: "Crear galería",
                    tip: "Subí una foto de portada antes de compartir: hace que el link se vea mucho más profesional al enviarlo por WhatsApp.",
                    final: true,
                },
            ],
        },
    ],
}

export default galeriesTour
