import { Globe } from "lucide-react"

const portfolioTour = {
    id: "setup-portfolio",
    icon: Globe,
    iconBg: "linear-gradient(135deg,#f0fdf4,#dcfce7)",
    iconColor: "#16a34a",
    title: "Configurar mi portfolio",
    description: "Creá tu página pública con tus datos, redes y galerías destacadas.",
    estimatedTime: "5 min",
    steps: [
        {
            id: "intro",
            title: "Tu vitrina profesional 🌐",
            body: "El portfolio es tu página pública en photobook.com.ar. Allí tus clientes van a poder conocerte, ver tu trabajo y contactarte directamente.",
            route: "/dashboard/portfolio",
            selector: null,
        },
        {
            id: "go-portfolio",
            title: "Ir a Mi PhotoBook",
            body: "Primero necesitás ir a la sección «Mi PhotoBook». En el menú lateral (o en el menú hamburguesa en celular) hacé clic en esa opción.",
            route: "/dashboard/portfolio",
            selector: "a[href='/dashboard/portfolio']",
            selectorText: "PhotoBook",
            tip: "Si no ves el menú, buscá el ícono de tres líneas (☰) en la esquina superior.",
        },
        {
            id: "activate-toggle",
            title: "Activar el portfolio",
            body: "Buscá el botón «Activo / Inactivo» en la parte superior de la página. Activalo para que tu portfolio sea visible al público.",
            route: "/dashboard/portfolio",
            selector: "button",
            selectorText: "Activo",
            selectorFallbackText: "Inactivo",
            tip: "Podés desactivarlo en cualquier momento sin perder tu configuración.",
        },
        {
            id: "slug",
            title: "Elegí tu URL personalizada",
            body: "Este es tu nombre en la URL pública. Lo que escribas acá va a quedar como tunombre.photobook.com.ar — elegí algo corto y fácil de recordar.",
            route: "/dashboard/portfolio",
            selector: "input[placeholder='tu-nombre']",
            selectParent: true,
            tip: "Usá solo letras minúsculas, números y guiones. Ej: «juan-garcia» o «fotojuan».",
        },
        {
            id: "avatar",
            title: "Subí tu foto de perfil",
            body: "Una buena foto de perfil genera confianza. Buscá el botón «Subir foto» en la sección de imágenes. Se muestra circular en tu portfolio.",
            route: "/dashboard/portfolio",
            selector: "button",
            selectorText: "Subir foto",
            selectorFallbackText: "Cambiar foto",
            tip: "Recomendado: foto cuadrada de al menos 400×400px, con buena iluminación.",
        },
        {
            id: "name-specialty",
            title: "Tu nombre y especialidad",
            body: "Completá tu nombre real y el nombre que aparecerá en el portfolio. También añadí tu especialidad.",
            route: "/dashboard/portfolio",
            selector: "input[placeholder='Tu nombre completo']",
            tip: "El nombre de portfolio puede ser tu nombre artístico o tu marca.",
        },
                {
            id: "specialty",
            title: "Tu nombre y especialidad",
            body: "Completá tu nombre real y el nombre que aparecerá en el portfolio. También añadí tu especialidad.",
            route: "/dashboard/portfolio",
            selector: "#specialty input",
            tip: "El nombre de portfolio puede ser tu nombre artístico o tu marca.",
        },
        {
            id: "bio",
            title: "Completá tu bio",
            body: "Contá en pocas líneas quién sos, qué tipo de fotografía hacés y en qué zona trabajás.",
            route: "/dashboard/portfolio",
            selector: "textarea[placeholder='Contá quién sos, tu estilo y experiencia...']",
            tip: "3-4 oraciones es suficiente. Mencioná tu ciudad y tipo de trabajo.",
        },
        {
            id: "instagram",
            title: "Redes sociales y contacto",
            body: "Hacé clic en esta sección para abrirla y vinculá tu Instagram, Facebook, TikTok y otras redes. Aparecen en tu portfolio para que los clientes te sigan.",
            route: "/dashboard/portfolio",
            selectorText: "Redes sociales y contacto",
            tip: "Instagram es la red más importante para fotógrafos. ¡No te la pierdas!",
        },
        {
            id: "tema",
            title: "Personalizá el tema de color",
            body: "Elegí la paleta de colores que va a tener tu portfolio público. Podés usar uno de los temas predefinidos o crear uno personalizado con tus propios colores.",
            route: "/dashboard/portfolio",
            selectorText: "Tema de color",
            tip: "Elegí colores que vayan con tu estilo fotográfico. Los temas oscuros funcionan muy bien para fotógrafos.",
        },
        {
            id: "imagenes",
            title: "Subí imágenes al portfolio",
            body: "Acá podés subir las fotos de muestra que se van a mostrar en tu portfolio público. Son las primeras imágenes que ven tus clientes al entrar.",
            route: "/dashboard/portfolio",
            selectorText: "Imágenes del portfolio",
            tip: "Subí entre 6 y 12 imágenes representativas de tu mejor trabajo.",
        },
        {
            id: "destacadas",
            title: "Galerías destacadas",
            body: "Seleccioná las galerías que quieras mostrar primero en tu portfolio. Aparecen como trabajos destacados y ayudan a los clientes a conocer tu estilo.",
            route: "/dashboard/portfolio",
            selectorText: "Galerías destacadas",
            tip: "Destacá galerías completas de bodas, retratos u otros trabajos que muestren tu versatilidad.",
        },
        {
            id: "save",
            title: "Guardar los cambios",
            body: "Cuando terminés de completar toda la info, guardá todo con el botón al final de la página.",
            route: "/dashboard/portfolio",
            selector: null,
            selectorText: "Guardar cambios",
            tip: "Los cambios se aplican de inmediato. Tu portfolio público se actualiza al instante.",
            final: true,
        },
    ],
}

export default portfolioTour